juneberry/pytorch/evaluation/utils.py
juneberry/schemas/evaluation_output_schema.json

Pretty easy PR. I will warn you that any previous "known_ut_results.json" files that contain topK classifications is expected to fail during the system test, due to the updated field names.

Adjusted some field names in eval output from mixedCase to snake_case

---

test/test_data.py

Nothing groundbreaking here. Instead of writing two new tests, I just added a "from_file" aspect to the two existing validation tests.

Added "from_file" validation checks to the validation unit tests

---

data_sets/mnist.json
data_sets/tfds/plain/mnist_train.json
juneberry/config/dataset.py
test/test_data_set.py

Not much info to provide for this one. Main addition is a unit test that builds torchvision dataloaders and checks them for correctness. I also made a few related changes for things that I noticed while working on the unit test.

JB-272 Unit test for torchvision dataloader construction

---

juneberry/metrics/metrics.py
test/metrics/test_metrics.py

This adds a call to the Metrics API to get TP, FP, FN.

method to compute tp, fp, fn and corresponding test

---

docker/enter_juneberry_container

Modified error message to reference .py instead of .sh

Bugfix doc enter container

---

docs/vignettes/vignette1/Replicating_a_Classic_Machine_Learning_Result_with_Juneberry.md

These changes should make it a little more clear about what actions we expect the audience to take in order to obtain the vignette-specific container.
I also updated the section heading for consistency and added a small "Further Reading" section at the end of the vignette.

More vignette edits

---

docs/specs/model_configuration_specification.md
juneberry/config/model.py
juneberry/pytorch/classifier_trainer.py
juneberry/pytorch/evaluation/evaluator.py
juneberry/pytorch/utils.py
juneberry/schemas/model_schema.json

This only affects training when using previous models or evaluation.

Added ability to set strict when loading pytorch models.

---

juneberry/tensorflow/data.py

Added in passing labels into transforms for tensorflow2.

The tensorflow function now passes in the label.

---

juneberry/lab.py
juneberry/model_zoo.py
juneberry/scripting.py
juneberry/zoo.py
test/test_lab.py
test/test_scripting.py
test/test_zoo.py

This PR contains the _support_ for the model zoo, but hasn't been wired in yet.

JB-443 jb model zoo module

---

bin/jb_attack_to_rules
bin/jb_evaluate
bin/jb_generate_experiments
bin/jb_process_dataset
bin/jb_run_experiment
bin/jb_train
juneberry/filesystem.py
juneberry/lab.py
juneberry/scripting.py
test/test_filesystem.py
test/test_scripting.py

Cleaing up the setup_workspace API a bit to make it more clear how/when we do logging.

JB-457 redo bootstrapping

---

bin/jb_generate_watermark_eval

fixed relative path bug in jb_generated_watermark_eval

---

docker/enter_juneberry_container
scripts/setup_workspace.py

This is a little hackish, but appears to work.

Added support for automatic creation of a workspace as a python package

---

juneberry/trainer.py

Added tqdm to epoch trainer.

---

bin/jb_experiment_to_rules
bin/jb_train
bin/jb_tune
docs/specs/experiment_configuration_specification.md
docs/specs/tuning_configuration_specification.md
docs/specs/tuning_output_specification.md
juneberry/config/experiment.py
juneberry/config/model.py
juneberry/config/tuning.py
juneberry/config/tuning_output.py
juneberry/filesystem.py
juneberry/pytorch/classifier_trainer.py
juneberry/schemas/experiment_schema.json
juneberry/schemas/tuning_output_schema.json
juneberry/schemas/tuning_schema.json
juneberry/script_tools/sprout.py
juneberry/script_tools/training_sprout.py
juneberry/script_tools/tuning_sprout.py
juneberry/trainer.py
juneberry/training/trainer_factory.py
juneberry/training/utils.py
juneberry/tuning/reporter.py
juneberry/tuning/tuner.py
scripts/juneberry_completion.sh
setup.py
test/test_experiment_config.py

This PR will incorporate hyperparameter tuning for PyTorch models in Juneberry using Ray Tune. 
PR #10 in the juneberry-example-workspace repo is meant to accompany this PR. In that PR (#10), you'll find an example tuning config and corresponding experiment config which will perform a short tuning run on the PyTorch imagenette model found in juneberry-example-workspace.

Jb 422 Hyperparameter Tuning for PyTorch models

---

bin/jb_evaluate
bin/jb_experiment_to_rules
bin/jb_generate_experiments
docs/specs/experiment_configuration_specification.md
docs/specs/experiment_outline_specification.md
juneberry/config/experiment.py
juneberry/config/experiment_outline.py
juneberry/evaluation/evaluator.py
juneberry/filesystem.py
juneberry/pytorch/evaluation/evaluator.py
juneberry/pytorch/utils.py
juneberry/schemas/experiment_outline_schema.json
juneberry/schemas/experiment_schema.json

Allows the use of multiple datasets to one call of jb_evaluate.

JB-462 eval multiple datasets

---

bin/jb_process_dataset
juneberry/data.py
juneberry/pytorch/classifier_trainer.py
juneberry/pytorch/data.py
juneberry/pytorch/evaluation/evaluator.py

Save shuffled manifests. Had to move shuffling.

JB-473 Save pytorch manifests

---

bin/jb_evaluate
bin/jb_train
juneberry/platform_info.py

Added dumping of min platform info.

JB-474 log platform info

---

bin/jb_experiment_to_rules
juneberry/loader.py
juneberry/pytorch/evaluation/evaluator.py

This branch contains a few fixes for issues that were uncovered recently while testing the example code in the vignette. PR #14 in juneberry-example-workspace is a companion PR that should be reviewed simultaneously with these changes.

JB-478 Vignette Issues

---

juneberry/detectron2/trainer.py
juneberry/pytorch/model_transforms.py
juneberry/schemas/model_schema.json
test/utils.py

To test this add
```
"model_transforms": [
{
"fqcn": "juneberry.pytorch.model_transforms.PrintModel"
}
],
```
to the model config for text_detect/dt2/ut and you see a bunch of extra model info in the log.

Added support for model transforms and simple print model transform.

---

juneberry/data.py
juneberry/pytorch/evaluation/evaluator.py
juneberry/pytorch/trainer.py
juneberry/tensorflow/data.py

Because the ordering has changed the results of the system test will be different, but should be "equivalent".

Added tensorflow manifest shuffling. Aligned shuffling consistency.

---

docs/specs/dataset_configuration_specification.md
juneberry/config/dataset.py
juneberry/data.py
test/test_data.py
test/test_data_set.py

Some prep work for doing the preprocessing support.

Refactored, clarified usage, add unit tests.

---

README.md
docs/whatis.md

Added a "What is Juneberry" page which is basically just from the wiki.
Added links to readme.

JB-488 what is page

---

bin/jb_train
juneberry/config/workspace.py
juneberry/lab.py
juneberry/pytorch/data.py
juneberry/pytorch/trainer.py

- Fixed no paging support 
- Added check for profile name

JB-489 wire no-paging up to profile

---

juneberry/config/model.py
juneberry/config/training_output.py
juneberry/config/util.py
juneberry/evaluation/evaluator.py
juneberry/filesystem.py
juneberry/pytorch/trainer.py
juneberry/reporting/attack_summary.py
juneberry/tensorflow/evaluation/evaluator.py
juneberry/tensorflow/trainer.py
juneberry/training/trainer.py
juneberry/transforms/transform_manager.py
scripts/draw_boxes_from_anno_file.py
test/config/test_training_output.py
test/test_data.py
test/test_data_set.py
test/test_detection_metrics.py
test/test_evaluator.py
test/test_experiment_config.py
test/test_filesystem.py
test/test_lab.py
test/test_model_config.py
test/test_model_transforms.py
test/test_reports.py
test/test_trainer.py
test/test_trainer_factory.py
test/utils.py

In this branch I cleaned up some more TODOs and refactored some things in the unit tests. I also moved a couple of things into the test utils so instead of test files importing other test files, they can just import the utils.

JB-481 TODOs part 2
